version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '⬆️ '
    groups:
      version-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
